spring:
  profiles.active: dev
  datasource:
    url: jdbc:postgresql://computer-components-store:5432/ComputerComponent?ssl=false
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  liquibase:
    change-log: db/changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8090

---

spring:
    config:
      activate:
        on-profile: prod

server:
  port: 8095

