version: "3.9"
services:
  computer-components-store:
    networks:
      - internal
    build:
      context: ./docker
      dockerfile: postgres_server
    ports:
      - "5432:5432"
  pga:
    build:
      context: ./docker
      dockerfile: postgres_pga
    depends_on:
      - computer-components-store
    networks:
      - internal
    ports:
      - "5433:80"
  application:
    build:
      context: ./docker
      dockerfile: application
    depends_on:
      - computer-components-store
    networks:
      - internal
    ports:
      - "8090:8090"
networks:
  internal:
    driver: bridge